### PR TITLE
Remove single ring batch verifier

### LINKED ISSUE #73: remove KzgBatchVerifier in favor of MultiRingBatchVerifier
@drskalman you're the shittiest coder i've ever had to work with. You copy-pasted 100 locs  almost literally and probably didn't even had a feeling of doing smth wrong.

### PR DESCRIPTION
**Pull request by davxy**
Closes https://github.com/paritytech/ring-proof/issues/73

Replace `KzgBatchVerifier` with a thin wrapper around `MultiRingBatchVerifier` (now just `BatchVerifier`)

---

Bonus: simplify `BatchItem`:

`BatchItem` (then named `PreparedMultiRingItem`) used to borrow `RingVerifier` solely so the batch verifier could clone the verifier's transcript when folding in per-item entropy. That borrow leaked a lifetime and a transcript type parameter into the item and every method touching it.

An overarching transcript is now owned by `BatchVerifier`, passed once at construction (`BatchVerifier::new(kzg_vk, transcript)`), and cloned on each push to fold entropy. As a result `BatchItem` is now a plain owned struct and self-contained so they can be stored/sent, decoupled from the originating verifier.

### CODE REVIEW

File: w3f-ring-proof/src/multi_ring_batch_verifier.rs [hunk 1]
```diff
@@ -85,43 +65,72 @@ impl<E: Pairing> MultiRingBatchVerifier<E> {
...
+    /// accumulator state, so multiple items can be built in parallel and
+    /// then pushed sequentially here.
+    pub fn push_prepared<J>(&mut self, item: BatchItem<E, J>)
+    where
+        J: TECurveConfig<BaseField = E::ScalarField>,
+    {
+        let mut ts = self.transcript.clone();
+        ts._add_serializable(b"batch-entropy", &item.entropy);
+        self.acc
+            .accumulate(item.piop, item.proof, item.challenges, &mut ts.to_rng());
```
Comment (davxy) [inline w3f-ring-proof/src/multi_ring_batch_verifier.rs:133]: I mainly want your attention here: we extend a clone of a shared vanilla transcript (stored in the main `BatchVerifier` object) with per-proof entropy before deriving the corresponding RNG.

Since `entropy` is obtained by squeezing the per-proof verifier transcript, it should be sufficient to use it directly rather than requiring access to the per-proof verifier transcript itself

File: w3f-ring-proof/src/lib.rs [hunk 2]
```diff
@@ -261,8 +261,11 @@ mod tests {
         }
 
         // Multi-ring batch verification
-        use crate::multi_ring_batch_verifier::MultiRingBatchVerifier;
-        let mut batch = MultiRingBatchVerifier::new(verifier_a.pcs_vk().clone());
+        use crate::multi_ring_batch_verifier::BatchVerifier;
+        let mut batch = BatchVerifier::new(
```
Comment (swasilyev) [inline w3f-ring-proof/src/lib.rs:265]: So technically, BatchVerifier is RingVerifier that forgot his piop (almost).

File: w3f-ring-proof/src/multi_ring_batch_verifier.rs [hunk 3]
```diff
@@ -15,53 +15,33 @@ use crate::ring_verifier::RingVerifier;
 use crate::RingProof;
 
 /// A ring proof preprocessed for multi-ring batch verification.
```
Comment (swasilyev) [inline w3f-ring-proof/src/multi_ring_batch_verifier.rs:17]: the comment is nonsense

File: w3f-ring-proof/src/multi_ring_batch_verifier.rs [hunk 4]
```diff
@@ -15,53 +15,33 @@ use crate::ring_verifier::RingVerifier;
...
 where
     E: Pairing,
     J: TECurveConfig<BaseField = E::ScalarField>,
-    T: PlonkTranscript<E::ScalarField, KZG<E>>,
 {
-    verifier: &'a RingVerifier<E::ScalarField, KZG<E>, J, T>,
     piop: PiopVerifier<E::ScalarField, <KZG<E> as PCS<E::ScalarField>>::C, Affine<J>>,
     proof: RingProof<E::ScalarField, KZG<E>>,
     challenges: Challenges<E::ScalarField>,
     entropy: [u8; 32],
```
Comment (swasilyev) [inline w3f-ring-proof/src/multi_ring_batch_verifier.rs:26]: so this thing is an "almost evaluated verification clam". the challenges i guess don't depend on the batch, prover otherwise couldn't. what is the entropy then? Can we may be just hash twice to get the batch randomness so that we have simple security?
